services:
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: "${DB_DATABASE:-devcollab}"
      POSTGRES_USER: "${DB_USERNAME:-devcollab}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-devcollab}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql:ro'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${DB_DATABASE:-devcollab} -U ${DB_USERNAME:-devcollab}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - .env
    build: .
    ports:
      - "${APP_PORT:-10000}:8080"
    environment:
      SERVICE: web
      RUN_MIGRATIONS: "${RUN_MIGRATIONS:-true}"
      RUN_SEEDERS: "${RUN_SEEDERS:-true}"
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_URL: "redis://redis:6379"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    env_file:
      - .env
    build: .
    environment:
      SERVICE: worker
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_URL: "redis://redis:6379"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  reverb:
    env_file:
      - .env
    build: .
    ports:
      - "${REVERB_PORT:-8080}:8080"
    environment:
      SERVICE: reverb
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_URL: "redis://redis:6379"
      REVERB_SERVER_HOST: 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
