/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "landing": [],
    "dashboard": [],
    "projects.index": [],
    "projects.create": [],
    "projects.store": [],
    "projects.edit": [
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.update": [
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.update-complete": [],
    "profile.destroy": [],
    "join-requests.index": [],
    "join-requests.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "join-requests.approve": [
        {
            "name": "joinRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "join-requests.reject": [
        {
            "name": "joinRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "join-requests.cancel": [
        {
            "name": "joinRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.show": [
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
  }
}

export {};